### ISSUE TITLE
zipp breaks on Python 3.10.0-alpha.7 & 3.10.0-beta.1

### ISSUE THREAD

**Issue by thepabloaguilar** [jaraco/zipp#72] opened 2021-04-25 20:38 UTC
Hello, one of my dependencies has `zipp` as a dependency and I'm trying to add __Python 3.10__ in my CI pipeline but for some reason on `zipp` installation it break:
```text
  • Installing zipp (3.4.1)

  JSONDecodeError

  Expecting value: line 1 column 1 (char 0)

  at /opt/hostedtoolcache/Python/3.10.0-beta.1/x64/lib/python3.10/json/decoder.py:355 in raw_decode
      351│         """
      352│         try:
      353│             obj, end = self.scan_once(s, idx)
      354│         except StopIteration as err:
    → 355│             raise JSONDecodeError("Expecting value", s, err.value) from None
      356│         return obj, end
      357│ 


  JSONDecodeError
```

You can check the full output [here](https://github.com/dry-python/returns/runs/2433180983?check_suite_focus=true)

**Comment by hoefling** [comment] 2021-05-09 13:06
@thepabloaguilar looks like a `poetry` issue to me; try disabling the experimental installer added in v1.1.0:
```
$ poetry config experimental.new-installer false
```

**Comment by jaraco** [comment] 2021-05-14 18:02
Thanks Oleg. Closing as invalid, but feel free to follow-up if there's something specific about this project that can address the issue.

**Closed by jaraco** 2021-05-14 18:02 UTC

**Comment by hoefling** [comment] 2021-05-14 18:49
@jaraco yepp, looks like the issue is indeed resolved for the OP: [new CI log](https://github.com/dry-python/returns/runs/2541136667) has no issues with `zipp` anymore, instead failing on compiling C extensions of another dependency.
