### ISSUE TITLE
Breaks under Python 2 because of broken more-itertools metadata

### ISSUE THREAD

**Issue by webknjaz** [jaraco/zipp#16] opened 2019-09-23 22:19 UTC
It looks like more-itertools==5.0.0 get pulled in as a dependency under Python 2 and is incompatible with Python 2.

https://ci.appveyor.com/project/CherryPy/cheroot/builds/27412242/job/ilh8p0lmaafm29t8#L39

Need smth like https://github.com/pytest-dev/pytest/pull/4774/files

**Comment by jaraco** [comment] 2019-09-26 20:13
The approach taken in that pytest reference is not sustainable. If we accept that change as the appropriate response to a project dropping support for a Python version, we'll be in an endless chase of our dependencies' dependencies. The solution is that all clients need to get pip 9 or later.

**Comment by jaraco** [comment] 2019-09-26 20:14
Also, this is a duplicate of #14 and #13.

**Closed by jaraco** 2019-09-26 20:13 UTC
