### ISSUE TITLE
zipp Causing our pytest command to fail

### ISSUE THREAD

**Issue by nicolasmoise** [jaraco/zipp#48] opened 2020-03-04 16:24 UTC
Our unit tests which were running fine before are now failing since the March3rd release of zipp.py with the following error:

```
pytest --cov-report xml

Traceback (most recent call last):

  File "/usr/local/bin/pytest", line 7, in <module>

    from pytest import main

  File "/usr/local/lib/python2.7/site-packages/pytest.py", line 9, in <module>

    from _pytest.config import main, UsageError, cmdline, hookspec, hookimpl

  File "/usr/local/lib/python2.7/site-packages/_pytest/config/__init__.py", line 19, in <module>

    import _pytest.hookspec  # the extension point definitions

  File "/usr/local/lib/python2.7/site-packages/_pytest/hookspec.py", line 3, in <module>

    from pluggy import HookspecMarker

  File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 16, in <module>

    from .manager import PluginManager, PluginValidationError

  File "/usr/local/lib/python2.7/site-packages/pluggy/manager.py", line 11, in <module>

    import importlib_metadata

  File "/usr/local/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>

    import zipp

  File "/usr/local/lib/python2.7/site-packages/zipp.py", line 153

SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/site-packages/zipp.py on line 154, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

script returned exit code 1
```

We have no made any changes to our unit tests or underlying code

**Comment by dlrust** [comment] 2020-03-04 18:08
We've also had a failure with the latest version

Don't have a ton of details, but looks like the latest 3.1.0 that you just released on pypi caused some errors and we had to revert versions.

This might be due to this system being on an older Debian 6 version?

```
    import timezonefinder
  File "/var/django/whitelabels/env/local/lib/python2.7/site-packages/timezonefinder/__init__.py", line 3, in <module>
    from .timezonefinder import TimezoneFinder
  File "/var/django/whitelabels/env/local/lib/python2.7/site-packages/timezonefinder/timezonefinder.py", line 9, in <module>
    from importlib_resources import open_binary
  File "/var/django/whitelabels/env/local/lib/python2.7/site-packages/importlib_resources/__init__.py", line 5, in <module>
    from ._compat import metadata
  File "/var/django/whitelabels/env/local/lib/python2.7/site-packages/importlib_resources/_compat.py", line 35, in <module>
    import importlib_metadata as metadata  # type: ignore
  File "/var/django/whitelabels/env/local/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/var/django/whitelabels/env/local/lib/python2.7/site-packages/zipp.py", line 153
SyntaxError: Non-ASCII character '\xe2' in file /var/django/whitelabels/env/local/lib/python2.7/site-packages/zipp.py on line 154, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

**Comment by kartikdutt18** [comment] 2020-03-04 18:08
Hmm, we are also facing something similar. They might be related.
[File "/home/vsts/work/1/s/build/src/mlpack/bindings/python/.eggs/importlib_metadata-1.5.0-py2.7.egg/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/home/vsts/work/1/s/build/src/mlpack/bindings/python/.eggs/zipp-3.1.0-py2.7.egg/zipp.py", line 217
    def open(self, mode='r', *args, pwd=None, **kwargs)](https://dev.azure.com/mlpack/mlpack/_build/results?buildId=794&view=logs&j=e7b65817-bf5f-5077-fec1-07c80f596179&t=41f26972-13d1-514c-278a-2f80dcb342eb&l=248)

**Comment by 0xFF1E071F** [comment] 2020-03-04 22:01
same issue here
did support for py2.7 dropped?

**Comment by jaraco** [comment] 2020-04-23 09:52
Python 2.7 support was dropped since zipp 2.x. I investigated this issue is #50, so although this issue was reported first, I'm marking this as a duplicate of the later one. Please see that issue for advice, which I'm 99% confident applies here.

**Closed by jaraco** 2020-04-23 09:52 UTC
