### ISSUE TITLE
zipp package appearing as editable in pipfile lock

### ISSUE THREAD

**Issue by ch3ck** [jaraco/zipp#66] opened 2020-11-12 23:19 UTC
This package is a sub dependency to some packages I use in my code. However, somehow once those packages are installed in `dev` mode. Something like this:
```bash
pipenv install zipp --dev
```

The `Pipfile.lock` appears as follows:
```json
"zipp": {
    "editable": true,
    "path": "."
}
```

I have to manually edit it to this:
```json
"zipp": {
    "hashes": [
        "sha256:64ad89efee774d1897a58607895d80789c59778ea02185dd846ac38394a8642b",
        "sha256:eed8ec0b8d1416b2ca33516a37a08892442f3954dee131e92cfd92d8fe3e7066"
    ],
    "version": "==3.3.0"
}
```

I don't know if there's a coming fix for this soon

**Comment by jaraco** [comment] 2020-12-17 03:09
I'm unsure why this issue is filed with this project. I'm not familiar with pipenv, so I don't know that the missed expectation is valid. I tried replicating the issue by installing pipenv in a venv and running the command, but when I did, in addition to triggering a segfault in Python 3.5 (even though I was using Python 3.9), the output shows what you expected above:

```
draft $ python -m venv env
draft $ env/bin/pip install pipenv
Collecting pipenv
  Downloading pipenv-2020.11.15-py2.py3-none-any.whl (3.9 MB)
     |████████████████████████████████| 3.9 MB 1.6 MB/s 
Requirement already satisfied: pip>=18.0 in ./env/lib/python3.9/site-packages (from pipenv) (20.2.3)
Requirement already satisfied: setuptools>=36.2.1 in ./env/lib/python3.9/site-packages (from pipenv) (49.2.1)
Collecting virtualenv-clone>=0.2.5
  Downloading virtualenv_clone-0.5.4-py2.py3-none-any.whl (6.6 kB)
Collecting certifi
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting virtualenv
  Using cached virtualenv-20.2.2-py2.py3-none-any.whl (5.7 MB)
Collecting six<2,>=1.9.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting appdirs<2,>=1.4.3
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting filelock<4,>=3.0.0
  Using cached filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting distlib<1,>=0.3.1
  Using cached distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Installing collected packages: virtualenv-clone, certifi, six, appdirs, filelock, distlib, virtualenv, pipenv
Successfully installed appdirs-1.4.4 certifi-2020.12.5 distlib-0.3.1 filelock-3.0.12 pipenv-2020.11.15 six-1.15.0 virtualenv-20.2.2 virtualenv-clone-0.5.4
WARNING: You are using pip version 20.2.3; however, version 20.3.3 is available.
You should consider upgrading via the '/Users/jaraco/draft/env/bin/python -m pip install --upgrade pip' command.
draft $ env/bin/pipenv install --dev zipp
Creating a virtualenv for this project...
Pipfile: /Users/jaraco/draft/Pipfile
Using /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 (3.9.0) to create virtualenv...
⠦ Creating virtual environment...created virtual environment CPython3.9.0.final.0-64 in 403ms
  creator CPython3Posix(dest=/Users/jaraco/.local/share/virtualenvs/draft-ojqnOjot, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/jaraco/Library/Application Support/virtualenv)
    added seed packages: pip==20.3.1, setuptools==50.3.2, wheel==0.36.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /Users/jaraco/.local/share/virtualenvs/draft-ojqnOjot
Creating a Pipfile for this project...
⠋ Installing...Installing zipp...
Adding zipp to Pipfile's [dev-packages]...
✔ Installation Succeeded 
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [packages] dependencies...
Updated Pipfile.lock (766016)!
Installing dependencies from Pipfile.lock (766016)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
draft $ python -V
Python 3.9.0
draft $ cat Pipfile.lock
{
    "_meta": {
        "hash": {
            "sha256": "41ab83003340ebd2133095c230e90b3ecbc0da49d8f2eff3e9dffa7ba4766016"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.9"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {
        "zipp": {
            "hashes": [
                "sha256:102c24ef8f171fd729d46599845e95c7ab894a4cf45f5de11a44cc7444fb1108",
                "sha256:ed5eee1974372595f9e416cc7bbeeb12335201d8081ca8a0743c954d4446e5cb"
            ],
            "index": "pypi",
            "version": "==3.4.0"
        }
    }
}
```

Now I have some cleanup to do.

Respectfully, I'm going to close this report as invalid, but if the issue is continuing, here's what I'll need to make progress on the issue; determine:

- if the issue is unique to specific versions of pipenv
- under what conditions the issue occurs
- if the issue is isolated to zipp or if it occurs with other packages
- (most importantly) what is it about this project that triggers the undesirable behavior

I would assume the undesirable behavior is a bug in pipenv until you can ascertain what it is about zipp that triggers the undesirable behavior and that pipenv has a reasonable expectation for zipp to present differently.

Good luck in your investigation.

**Closed by jaraco** 2020-12-17 03:09 UTC
