### ISSUE TITLE
3.4.1 breaks python 2.7 installs

### ISSUE THREAD

**Issue by gaborbernat** [jaraco/zipp#71] opened 2021-04-06 14:03 UTC
pip does pull it in and then fails with:

```
       'find_namespace: directive is unsupported on Python < 3.3')
    distutils.errors.DistutilsOptionError: find_namespace: directive is unsupported on Python < 3.3
    ----------------------------------------
```

Could be a pip/setuptools issue too, but interesting how it doesn't happen with 3.4.0... For now, the only working workaround seems to be to add another dependency where this package is pulled in (diff_cover, pytest) with ``zipp<2``.

**Comment by jaraco** [comment] 2021-04-06 15:31
This is a duplicate of #70.

**Closed by jaraco** 2021-04-06 15:31 UTC
